// Local CTF Data Structure - Auto-generated
// Generated by extract_challenges.py
// Challenge names use ACTUAL folder names!

const localCTFData = [
    {
        "id": 1,
        "title": "Osint 1",
        "status": "active",
        "description": "A collection of OSINT challenges. Test your intelligence gathering skills!",
        "year": "2024",
        "totalChallenges": 9,
        "baseFolder": "CTFs/OSINT_1",
        "githubUrl": "https://github.com/yourusername/your-repo",
        "answersUrl": "https://github.com/yourusername/your-repo/tree/main/CTFs/OSINT_1/Answers",
        "challenges": {
            "easy": [
                {
                    "name": "Jabalya",
                    "description": "While scrolling on my accounts I found this beautiful image. but the browser crashed before I enter the author's profile and I noticed date was Dec,2014. so can you help me find the ID of the Post?",
                    "passwordFormat": "Social Media Post/Tweet ID",
                    "files": [
                        "Flag.rar",
                        "Image.jpg",
                        "Jabalya.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Easy/Jabalya",
                    "imageUrl": "CTFs/OSINT_1/Easy/Jabalya/Image.jpg",
                    "answer": "550034078658228224"
                },
                {
                    "name": "Jenin",
                    "description": "I was going through internet looking for items from 1900. but one of these was interesting so can you find out written by who in the past?",
                    "passwordFormat": "written_by_name",
                    "files": [
                        "Flag.rar",
                        "Jenin.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Easy/Jenin",
                    "answer": "Florence_Clarke"
                },
                {
                    "name": "Khan Yunis",
                    "description": "I was on a trip to the beautiful Palestine. and on the 2nd day, I just fell off and went to the hospital the people were very nice and kind. here is an image of the hospital I really recommend it.",
                    "passwordFormat": "Name_Of_The_Hospital_In_English",
                    "files": [
                        "Flag.rar",
                        "Image.png",
                        "Khan Yunis.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Easy/Khan Yunis",
                    "imageUrl": "CTFs/OSINT_1/Easy/Khan Yunis/Image.png",
                    "answer": "Algerian_Hospital_the_specialist"
                },
                {
                    "name": "Nablus",
                    "description": "I was on a spy mission to catch a criminal calling himself \"sl4y3rz\". so I need you help to find his device encryption key.",
                    "passwordFormat": "device encryption key",
                    "files": [
                        "Flag.rar",
                        "Nablus.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Easy/Nablus",
                    "answer": "0121aac29ec0d18fd072201142785ae50ea7b32c7127cd8959eab283979af1fc15010a"
                }
            ],
            "medium": [
                {
                    "name": "Deir al-Balah",
                    "description": "Find WWW Password.",
                    "passwordFormat": "Check the file for format",
                    "files": [
                        "Deir al-Balah.txt",
                        "Flag.rar"
                    ],
                    "localFolder": "CTFs/OSINT_1/Medium/Deir al-Balah",
                    "answer": "me@myhost.edu"
                },
                {
                    "name": "Gaza",
                    "description": "finspy A commercial spyware program used by law enforcement and government agencies worldwide. I was on a mission to look for something about this spyware program and I need your help I need you to find the MD5 of the oldest document.",
                    "passwordFormat": "Doucment MD5",
                    "files": [
                        "Flag.rar",
                        "Gaza.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Medium/Gaza",
                    "answer": "d34985f473df6880c77d5d132cdc70c1"
                },
                {
                    "name": "Ramallah",
                    "description": "I went on a vacation and visited one of the local restaurants it wasn't so bad so when I decided to visit this place again, I couldn't remember its name because it was written in Arabic, but I was so lucky I found a photo in my gallery of the place near that restaurant so can help me find that restaurant?",
                    "passwordFormat": "Restaurant Social Media's Profile ID",
                    "files": [
                        "Flag.rar",
                        "image.png",
                        "Ramallah.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Medium/Ramallah",
                    "imageUrl": "CTFs/OSINT_1/Medium/Ramallah/image.png",
                    "answer": "100074221443968"
                }
            ],
            "hard": [
                {
                    "name": "Jerusalem",
                    "description": "Here is a small story about this image: This is John Scopes and his defense lawyers. He was a high school teacher who was arrested for teaching evolution, breaking a new law called the Butler Act. I could find this old image for you. but we need to read more about it. so I need your help to find some information.",
                    "passwordFormat": "This is John Scopes and his defense lawyers. He was a high school teacher who was arrested for teaching evolution, breaking a new law called the Butler Act. I could find this old image for you. but we need to read more about it. so I need your help to find some information.",
                    "files": [
                        "Flag.rar",
                        "Image.png",
                        "Jerusalem.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Hard/Jerusalem",
                    "imageUrl": "CTFs/OSINT_1/Hard/Jerusalem/Image.png",
                    "answer": "THE_EVENING_STAR_32c562cbb1f3e39992d52fe767f4ebd7"
                },
                {
                    "name": "Rafah",
                    "description": "Hey there, buddy. I've got a critical mission for you. There's a Russian cybercriminal we need to track down. He's running a Telegram channel where he sells personal data and access to hacked devices, plus he’s extorting victims for cash. The good news? There's a decryption script floating around the internet. Can you track down the MD5 of that script and find out when the Telegram channel was created? Good luck!",
                    "passwordFormat": "MD5_DD-MM-YYYY_HH:MM",
                    "files": [
                        "Flag.rar",
                        "Rafah.txt"
                    ],
                    "localFolder": "CTFs/OSINT_1/Hard/Rafah",
                    "answer": "09ce91b4f137a4cbc1496d3791c6e75b_14-04-2023_12:39"
                }
            ]
        }
    }
];

// Make data globally available
window.localCTFData = localCTFData;